[package]
name = "march"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.3"
rand = "0.8.5"

[dev-dependencies]
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"